sudo: true
dist: trusty
before_install:
    - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) universe"
    - sudo apt-get update
    - sudo apt-get install -y cabal-install
    - sudo cabal update
    - sudo cabal install shellcheck
    - sudo pip install pre-commit
script:
    - export PATH=/home/travis/.cabal/bin:$PATH
    - make test
deploy:
  provider: releases
  api_key: $CI_USER_TOKEN
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
